import './components/choices.js'
import './components/range-slider'
import './components/swiper.js'
import './components/tooltip.js'
import './components/dropdown'
import './components/catalogTags'
import './components/ratingMainSection'
